### ISSUE TITLE
[Tracking] HSM Support

### ISSUE THREAD

**Issue by hansl** [l-1-labs/many-rs#16]
Our CLI tools should support using a YubiKey / HSM.

**Comment by fmorency** [comment]
EDDSA is only officially supported by PKCS#11 v3.0, which is still not widespread, ex., the Yubikey PKCS#11 module supports v2.40.

Some projects such as https://github.com/Mastercard/pkcs11-tools, https://github.com/opendnssec/SoftHSMv2 and https://github.com/danni/python-pkcs11 have backported EDDSA from PKCS#11 v3.0 to v2.40.

None of the Rust PKCS#11 crates, namely https://crates.io/crates/pkcs11 and https://crates.io/crates/cryptoki, seem to support EDDSA at the moment of writing these lines.

The cryptoki project is open to an EDDSA contribution, as mentioned on https://github.com/parallaxsecond/rust-cryptoki/issues/87

**Comment by fmorency** [comment]
After disscusing with @hansl, we decided to only focus on ECDSA at the moment.

**Comment by hansl** [comment]
Integration is going well. One issue blocking right now but done by EOW and demo next ENG Weekly.

**Comment by hansl** [comment]
There's no more eng work than #28 for this.
