### ISSUE TITLE
Configure CI to run on PR

### ISSUE THREAD

**Issue by fmorency** [l-1-labs/many-rs#37]
We want to be able to run the CI suite on PR. See

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories-2

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

@hansl WDYT?

**Comment by hansl** [comment]
Sounds good to me. We don't have any secrets anyway.
